server:
  port: 7777

spring:
  application:
    name: biba-JPA

  datasource:
    url: jdbc:postgresql://postgres:5432/ProjectKEK
    username: admin
    password: '****'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: kafka1:9092
#    ,kafka2:9093,kafka3:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://schema-registry:8081

event:
  topic: events
  generation:
    interval-ms: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://alloy:4318/v1/traces

logging:
  level:
    io.opentelemetry: DEBUG
    org.springframework.boot.actuate.autoconfigure.tracing: DEBUG
    io.micrometer.tracing: DEBUG

debug: true