services:
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - network1
      - network2
    ports:
      - "80:80"
    volumes:
      # Конфиги
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets/:/etc/nginx/snippets/
      # Логи
      - ./logs:/var/log/nginx
    depends_on:
      - postgres
      - BIBA
      - BOBA

  postgres:
    image: postgres:15
    container_name: postgresPKEK
    environment:
      POSTGRES_DB: ProjectKEK
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '****'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network1

  BIBA:
    container_name: BIBA
    build:
      context: ./ProjectBIBA
      dockerfile: Dockerfile
    image: biba-image
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - network1
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  BOBA:
    container_name: BOBA
    build:
      context: ./ProjectBOBA
      dockerfile: Dockerfile
    image: boba-image
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - network1
    ports:
      - "8082:8080"
    depends_on:
      - postgres

networks:
  network1:
    name: network1
  network2:
    name: network2

volumes:
  postgres_data: