services:
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - network1
      - network2
    ports:
      - "80:80"
    volumes:
      # Конфиги
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets/:/etc/nginx/snippets/
      # Логи
      - ./logs:/var/log/nginx

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ProjectKEK
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '****'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U admin -d ProjectKEK"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network1

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:****@postgres:5432/ProjectKEK?sslmode=disable"
    healthcheck:
      test: ["CMD","wget","--spider","-q","http://localhost:9187/metrics"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - network1


  biba:
    image: biba-image
    container_name: biba
    build:
      context: ./ProjectBIBA
      dockerfile: Dockerfile
    environment:
      OTEL_SERVICE_NAME: biba-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4318/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none
      OTEL_RESOURCE_ATTRIBUTES: service.version=1.0.0,deployment.environment=docker
    networks:
      - network1
    ports:
      - "7777:7777"
    depends_on:
      kafka1:
        condition: service_healthy
#      kafka2:
#        condition: service_healthy
#      kafka3:
#        condition: service_healthy
      schema-registry:
        condition: service_healthy

  boba:
    image: boba-image
    container_name: boba
    build:
      context: ./ProjectBOBA
      dockerfile: Dockerfile
    environment:
      OTEL_SERVICE_NAME: boba-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4318/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none
      OTEL_RESOURCE_ATTRIBUTES: service.version=1.0.0,deployment.environment=docker
    networks:
      - network1
    ports:
      - "7778:7778"
    depends_on:
      kafka1:
        condition: service_healthy
      #      kafka2:
      #        condition: service_healthy
      #      kafka3:
      #        condition: service_healthy
      schema-registry:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - network1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    healthcheck:
      test: ["CMD","wget","--spider","-q","http://localhost:9090/-/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - network1
    healthcheck:
      test: ["CMD","wget","--spider","-q","http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    healthcheck:
      test: ["CMD","echo","ruok","|","nc","localhost","2181","|","grep","imok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network1

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
    volumes:
      - kafka1_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - network1

#  kafka2:
#    image: confluentinc/cp-kafka:7.5.0
#    container_name: kafka2
#    hostname: kafka2
#    ports:
#      - "9093:9093"
#    volumes:
#      - kafka2_data:/var/lib/kafka/data
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    healthcheck:
#      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9093", "--list" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    depends_on:
#      zookeeper:
#        condition: service_healthy
#    networks:
#      - network1
#
#  kafka3:
#    image: confluentinc/cp-kafka:7.5.0
#    container_name: kafka3
#    hostname: kafka3
#    ports:
#      - "9094:9094"
#    volumes:
#      - kafka3_data:/var/lib/kafka/data
#    environment:
#      KAFKA_BROKER_ID: 3
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    healthcheck:
#      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9094", "--list" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    depends_on:
#      zookeeper:
#        condition: service_healthy
#    networks:
#      - network1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    ports:
      - "8081:8081"
    volumes:
      - schema_registry_data:/etc/schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    depends_on:
      kafka1:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    networks:
      - network1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/subjects" ]
      interval: 10s
      timeout: 5s
      retries: 5


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8070:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
#      - ,kafka2:9093,kafka3:9094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8081
    depends_on:
      kafka1:
        condition: service_healthy
#      kafka2:
#        condition: service_healthy
#      kafka3:
#        condition: service_healthy
      schema-registry:
        condition: service_healthy
    networks:
      - network1
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    restart: unless-stopped
    command:
      - "--kafka.server=kafka1:9092"
#      - "--kafka.server=kafka2:9093"
#      - "--kafka.server=kafka3:9094"
    healthcheck:
      test: ["CMD","wget","--spider","-q","http://localhost:9308/metrics"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      kafka1:
        condition: service_healthy
#      kafka2:
#        condition: service_healthy
#      kafka3:
#        condition: service_healthy
    networks:
      - network1


  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    user: "root"
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_chunks:/tmp/loki/chunks
      - loki_index:/tmp/loki/index
      - loki_rules:/tmp/loki/rules
    networks:
      - network1

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    volumes:
      - ./monitoring/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"
    networks:
      - network1

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    user: root
    ports:
      - "9080:9080"  # HTTP-интерфейс Alloy (по умолчанию)
      - "4317:4317"  # OTLP gRPC (важно)
      - "4318:4318"  # OTLP HTTP (если нужен)
    volumes:
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - //var/run/docker.sock:/var/run/docker.sock
#      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
    environment:
      GRAFANA_LOKI_URL: http://loki:3100/loki/api/v1/push  # локальный Loki
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:9080
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    networks:
      - network1

networks:
  network1:
    name: network1
  network2:
    name: network2

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  kafka1_data:
#  kafka2_data:
#  kafka3_data:
  zookeeper_data:
  zookeeper_log:
  schema_registry_data:
  loki_data:
  loki_chunks:
  loki_index:
  loki_rules:
  tempo_data: