management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,trace
  endpoint:
    trace:
      enabled: true

#otel:
#  service:
#    name: ${spring.application.name}
#  exporter:
#    jaeger:
#      endpoint: http://jaeger:14250
#  traces:
#    exporter: jaeger

logging:
  config: classpath:logback-spring.xml
  level:
    io.opentelemetry: DEBUG
    com.projectkek: DEBUG