global:
  scrape_interval: 15s
#  evaluation_interval: 30s

scrape_configs:
  - job_name:  'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'biba'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['biba:7777']

  - job_name: 'boba'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['boba:7778']

  - job_name: 'unkn'
    static_configs:
      - targets: ['unkn:8083']

  - job_name: 'pg-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']


#  - job_name: 'one_job'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 30s
#    static_configs:
#      - targets:
#          - 'BIBA:8080'
#          - 'BOBA:8080'
#        labels:
#          group: 'myBi&Bo_group'
#          environment: 'docker'
