openapi: 3.0.3
info:
  title: "Boba API"
  version: "1.0"
  description: "описание АПИ Боба!!"

servers:
  - url: http://localhost:7778
    description: Локалка

paths:
  /:
    get:
      tags:
        - ExampleBOBA
      summary: Метод получения ExampleBoba
      operationId: getAllExampleBoba
      responses:
        '200':
          description: Успех получения exampleBobba
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExampleBoba'

components:
  schemas:
    ExampleBoba:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      required:
        - id
        - name