server:
  port: 7778

spring:
  application:
    name: boba-JDBC

  datasource:
    url: jdbc:postgresql://postgres:5432/ProjectKEK
    username: admin
    password: '****'

  kafka:
    bootstrap-servers: kafka1:9092
    #    ,kafka2:9093,kafka3:9094
    consumer:
      group-id: event-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://schema-registry:8081
      specific.avro.reader: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://alloy:4318/v1/traces

logging:
  level:
    io.opentelemetry: DEBUG
    org.springframework.boot.actuate.autoconfigure.tracing: DEBUG
    io.micrometer.tracing: DEBUG

debug: true